CREATE VIEW [dbo].[SensorDataView]
	AS 
	SELECT [Id]
      ,[EventDateTime]
      ,[SensorId]
      ,[Value]
      ,cast([EventDateTime] as date) AS [date]
      ,cast([EventDateTime] as time) AS [time]
      ,(DATEPART(week,[EventDateTime])) as [week]
      ,(DATEPART(dd,[EventDateTime])) as [day]
      ,(DATEPART(mm,[EventDateTime])) as [month]
      ,(DATEPART(hh,[EventDateTime])) as [hour]      
	  ,(DATEPART(MI,[EventDateTime])) as [minute]   
	  ,(DATEPART(YYYY,[EventDateTime])) as [year] 
  FROM [dbo].[SensorData]
