//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHouse.EfRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Sensors = new HashSet<Sensor>();
        }
    
        public int Id { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Token { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Sensor> Sensors { get; set; }
    }
}
