//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHouse.EfRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public Sensor()
        {
            this.SensorData = new HashSet<SensorData>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SensorTypeId { get; set; }
        public string Location { get; set; }
        public int DeviceId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual SensorType SensorType { get; set; }
        public virtual ICollection<SensorData> SensorData { get; set; }
    }
}
