//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHouse.EfRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorDataView
    {
        public int Id { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int SensorId { get; set; }
        public double Value { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> hour { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> minute { get; set; }
    }
}
