//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHouse.EfRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorType
    {
        public SensorType()
        {
            this.Sensors = new HashSet<Sensor>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string Dimension { get; set; }
    
        public virtual ICollection<Sensor> Sensors { get; set; }
    }
}
